/**
 * Asset Map for Static DISTAR Card Images
 * 
 * React Native requires static require() calls for bundled assets.
 * This maps asset paths to their require() statements.
 * 
 * Generated from actual files in assets/en-US directory
 * DO NOT EDIT THIS FILE MANUALLY
 */

// Image assets
const IMAGE_ASSETS: Record<string, any> = {
  'assets/en-US/001-i/image.png': require('../../assets/en-US/001-i/image.png'),
  'assets/en-US/002-ar/image.png': require('../../assets/en-US/002-ar/image.png'),
  'assets/en-US/003-h/image.png': require('../../assets/en-US/003-h/image.png'),
  'assets/en-US/004-ai/image.png': require('../../assets/en-US/004-ai/image.png'),
  'assets/en-US/005-school/image.png': require('../../assets/en-US/005-school/image.png'),
  'assets/en-US/006-route/image.png': require('../../assets/en-US/006-route/image.png'),
  'assets/en-US/007-mood/image.png': require('../../assets/en-US/007-mood/image.png'),
  'assets/en-US/008-might/image.png': require('../../assets/en-US/008-might/image.png'),
  'assets/en-US/009-the-kid-can-kick/image.png': require('../../assets/en-US/009-the-kid-can-kick/image.png'),
  'assets/en-US/010-the-sun-is-hot/image.png': require('../../assets/en-US/010-the-sun-is-hot/image.png'),
  'assets/en-US/011-we-had-a-great-day/image.png': require('../../assets/en-US/011-we-had-a-great-day/image.png'),
  'assets/en-US/012-we-went-to-the-park/image.png': require('../../assets/en-US/012-we-went-to-the-park/image.png'),
};

/**
 * Get image source for a given asset path
 */
export function getImageSource(assetPath: string): any {
  if (assetPath.startsWith('http://') || assetPath.startsWith('https://')) {
    return { uri: assetPath };
  }
  
  const mappedAsset = IMAGE_ASSETS[assetPath];
  if (mappedAsset) {
    return mappedAsset;
  }
  
  console.warn(`Asset not found in map: ${assetPath}`);
  return { uri: assetPath };
}

/**
 * Check if an image asset exists
 */
export function hasImageAsset(assetPath: string): boolean {
  return assetPath in IMAGE_ASSETS || 
         assetPath.startsWith('http://') || 
         assetPath.startsWith('https://');
}
