/**
 * Audio Asset Map for Static DISTAR Card Audio
 * 
 * React Native requires static require() calls for bundled assets.
 * This maps audio asset paths to their require() statements.
 * 
 * Generated from actual files in assets/en-US directory
 * DO NOT EDIT THIS FILE MANUALLY
 */

// Audio assets
const AUDIO_ASSETS: Record<string, any> = {
  'assets/en-US/001-i/audio.mp3': require('../../assets/en-US/001-i/audio.mp3'),
  'assets/en-US/001-i/great-job.mp3': require('../../assets/en-US/001-i/great-job.mp3'),
  'assets/en-US/001-i/no-input.mp3': require('../../assets/en-US/001-i/no-input.mp3'),
  'assets/en-US/001-i/prompt.mp3': require('../../assets/en-US/001-i/prompt.mp3'),
  'assets/en-US/001-i/try-again.mp3': require('../../assets/en-US/001-i/try-again.mp3'),
  'assets/en-US/002-ar/audio.mp3': require('../../assets/en-US/002-ar/audio.mp3'),
  'assets/en-US/002-ar/great-job.mp3': require('../../assets/en-US/002-ar/great-job.mp3'),
  'assets/en-US/002-ar/no-input.mp3': require('../../assets/en-US/002-ar/no-input.mp3'),
  'assets/en-US/002-ar/prompt.mp3': require('../../assets/en-US/002-ar/prompt.mp3'),
  'assets/en-US/002-ar/try-again.mp3': require('../../assets/en-US/002-ar/try-again.mp3'),
  'assets/en-US/003-h/audio.mp3': require('../../assets/en-US/003-h/audio.mp3'),
  'assets/en-US/003-h/great-job.mp3': require('../../assets/en-US/003-h/great-job.mp3'),
  'assets/en-US/003-h/no-input.mp3': require('../../assets/en-US/003-h/no-input.mp3'),
  'assets/en-US/003-h/prompt.mp3': require('../../assets/en-US/003-h/prompt.mp3'),
  'assets/en-US/003-h/try-again.mp3': require('../../assets/en-US/003-h/try-again.mp3'),
  'assets/en-US/004-ai/audio.mp3': require('../../assets/en-US/004-ai/audio.mp3'),
  'assets/en-US/004-ai/great-job.mp3': require('../../assets/en-US/004-ai/great-job.mp3'),
  'assets/en-US/004-ai/no-input.mp3': require('../../assets/en-US/004-ai/no-input.mp3'),
  'assets/en-US/004-ai/prompt.mp3': require('../../assets/en-US/004-ai/prompt.mp3'),
  'assets/en-US/004-ai/try-again.mp3': require('../../assets/en-US/004-ai/try-again.mp3'),
  'assets/en-US/005-school/audio-sounded.mp3': require('../../assets/en-US/005-school/audio-sounded.mp3'),
  'assets/en-US/005-school/audio.mp3': require('../../assets/en-US/005-school/audio.mp3'),
  'assets/en-US/005-school/great-job.mp3': require('../../assets/en-US/005-school/great-job.mp3'),
  'assets/en-US/005-school/no-input.mp3': require('../../assets/en-US/005-school/no-input.mp3'),
  'assets/en-US/005-school/prompt.mp3': require('../../assets/en-US/005-school/prompt.mp3'),
  'assets/en-US/005-school/try-again.mp3': require('../../assets/en-US/005-school/try-again.mp3'),
  'assets/en-US/006-route/audio-sounded.mp3': require('../../assets/en-US/006-route/audio-sounded.mp3'),
  'assets/en-US/006-route/audio.mp3': require('../../assets/en-US/006-route/audio.mp3'),
  'assets/en-US/006-route/great-job.mp3': require('../../assets/en-US/006-route/great-job.mp3'),
  'assets/en-US/006-route/no-input.mp3': require('../../assets/en-US/006-route/no-input.mp3'),
  'assets/en-US/006-route/prompt.mp3': require('../../assets/en-US/006-route/prompt.mp3'),
  'assets/en-US/006-route/try-again.mp3': require('../../assets/en-US/006-route/try-again.mp3'),
  'assets/en-US/007-mood/audio-sounded.mp3': require('../../assets/en-US/007-mood/audio-sounded.mp3'),
  'assets/en-US/007-mood/audio.mp3': require('../../assets/en-US/007-mood/audio.mp3'),
  'assets/en-US/007-mood/great-job.mp3': require('../../assets/en-US/007-mood/great-job.mp3'),
  'assets/en-US/007-mood/no-input.mp3': require('../../assets/en-US/007-mood/no-input.mp3'),
  'assets/en-US/007-mood/prompt.mp3': require('../../assets/en-US/007-mood/prompt.mp3'),
  'assets/en-US/007-mood/try-again.mp3': require('../../assets/en-US/007-mood/try-again.mp3'),
  'assets/en-US/008-might/audio-sounded.mp3': require('../../assets/en-US/008-might/audio-sounded.mp3'),
  'assets/en-US/008-might/audio.mp3': require('../../assets/en-US/008-might/audio.mp3'),
  'assets/en-US/008-might/great-job.mp3': require('../../assets/en-US/008-might/great-job.mp3'),
  'assets/en-US/008-might/no-input.mp3': require('../../assets/en-US/008-might/no-input.mp3'),
  'assets/en-US/008-might/prompt.mp3': require('../../assets/en-US/008-might/prompt.mp3'),
  'assets/en-US/008-might/try-again.mp3': require('../../assets/en-US/008-might/try-again.mp3'),
  'assets/en-US/009-the-kid-can-kick/audio.mp3': require('../../assets/en-US/009-the-kid-can-kick/audio.mp3'),
  'assets/en-US/009-the-kid-can-kick/great-job.mp3': require('../../assets/en-US/009-the-kid-can-kick/great-job.mp3'),
  'assets/en-US/009-the-kid-can-kick/no-input.mp3': require('../../assets/en-US/009-the-kid-can-kick/no-input.mp3'),
  'assets/en-US/009-the-kid-can-kick/prompt.mp3': require('../../assets/en-US/009-the-kid-can-kick/prompt.mp3'),
  'assets/en-US/009-the-kid-can-kick/try-again.mp3': require('../../assets/en-US/009-the-kid-can-kick/try-again.mp3'),
  'assets/en-US/010-the-sun-is-hot/audio.mp3': require('../../assets/en-US/010-the-sun-is-hot/audio.mp3'),
  'assets/en-US/010-the-sun-is-hot/great-job.mp3': require('../../assets/en-US/010-the-sun-is-hot/great-job.mp3'),
  'assets/en-US/010-the-sun-is-hot/no-input.mp3': require('../../assets/en-US/010-the-sun-is-hot/no-input.mp3'),
  'assets/en-US/010-the-sun-is-hot/prompt.mp3': require('../../assets/en-US/010-the-sun-is-hot/prompt.mp3'),
  'assets/en-US/010-the-sun-is-hot/try-again.mp3': require('../../assets/en-US/010-the-sun-is-hot/try-again.mp3'),
  'assets/en-US/011-we-had-a-great-day/audio.mp3': require('../../assets/en-US/011-we-had-a-great-day/audio.mp3'),
  'assets/en-US/011-we-had-a-great-day/great-job.mp3': require('../../assets/en-US/011-we-had-a-great-day/great-job.mp3'),
  'assets/en-US/011-we-had-a-great-day/no-input.mp3': require('../../assets/en-US/011-we-had-a-great-day/no-input.mp3'),
  'assets/en-US/011-we-had-a-great-day/prompt.mp3': require('../../assets/en-US/011-we-had-a-great-day/prompt.mp3'),
  'assets/en-US/011-we-had-a-great-day/try-again.mp3': require('../../assets/en-US/011-we-had-a-great-day/try-again.mp3'),
  'assets/en-US/012-we-went-to-the-park/audio.mp3': require('../../assets/en-US/012-we-went-to-the-park/audio.mp3'),
  'assets/en-US/012-we-went-to-the-park/great-job.mp3': require('../../assets/en-US/012-we-went-to-the-park/great-job.mp3'),
  'assets/en-US/012-we-went-to-the-park/no-input.mp3': require('../../assets/en-US/012-we-went-to-the-park/no-input.mp3'),
  'assets/en-US/012-we-went-to-the-park/prompt.mp3': require('../../assets/en-US/012-we-went-to-the-park/prompt.mp3'),
  'assets/en-US/012-we-went-to-the-park/try-again.mp3': require('../../assets/en-US/012-we-went-to-the-park/try-again.mp3'),
};

/**
 * Get audio source for a given asset path
 */
export function getAudioSource(assetPath: string): any {
  if (assetPath.startsWith('http://') || assetPath.startsWith('https://')) {
    return { uri: assetPath };
  }
  
  const mappedAsset = AUDIO_ASSETS[assetPath];
  if (mappedAsset) {
    return mappedAsset;
  }
  
  console.warn(`Audio asset not found in map: ${assetPath}`);
  return null;
}

/**
 * Check if an audio asset exists
 */
export function hasAudioAsset(assetPath: string): boolean {
  return assetPath in AUDIO_ASSETS || 
         assetPath.startsWith('http://') || 
         assetPath.startsWith('https://');
}
