/**
 * Audio Asset Map for Static DISTAR Card Audio Files
 * 
 * React Native requires static require() calls for bundled assets.
 * This maps audio asset paths to their require() statements.
 * 
 * Generated by scripts/generate-cards.ts
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * NOTE: All require() statements must be static (no variables in the path)
 */

// Audio assets for cards - using static require() statements
const AUDIO_ASSETS: Record<string, any> = {
  'assets/en-US/001-o/audio.mp3': require('../../assets/en-US/001-o/audio.mp3'),
  'assets/en-US/001-o/great-job.mp3': require('../../assets/en-US/001-o/great-job.mp3'),
  'assets/en-US/001-o/no-input.mp3': require('../../assets/en-US/001-o/no-input.mp3'),
  'assets/en-US/001-o/prompt.mp3': require('../../assets/en-US/001-o/prompt.mp3'),
  'assets/en-US/001-o/try-again.mp3': require('../../assets/en-US/001-o/try-again.mp3'),
  'assets/en-US/002-ing/audio.mp3': require('../../assets/en-US/002-ing/audio.mp3'),
  'assets/en-US/002-ing/great-job.mp3': require('../../assets/en-US/002-ing/great-job.mp3'),
  'assets/en-US/002-ing/no-input.mp3': require('../../assets/en-US/002-ing/no-input.mp3'),
  'assets/en-US/002-ing/prompt.mp3': require('../../assets/en-US/002-ing/prompt.mp3'),
  'assets/en-US/002-ing/try-again.mp3': require('../../assets/en-US/002-ing/try-again.mp3'),
  'assets/en-US/003-zip/audio-sounded.mp3': require('../../assets/en-US/003-zip/audio-sounded.mp3'),
  'assets/en-US/003-zip/audio.mp3': require('../../assets/en-US/003-zip/audio.mp3'),
  'assets/en-US/003-zip/great-job.mp3': require('../../assets/en-US/003-zip/great-job.mp3'),
  'assets/en-US/003-zip/no-input.mp3': require('../../assets/en-US/003-zip/no-input.mp3'),
  'assets/en-US/003-zip/prompt.mp3': require('../../assets/en-US/003-zip/prompt.mp3'),
  'assets/en-US/003-zip/try-again.mp3': require('../../assets/en-US/003-zip/try-again.mp3'),
  'assets/en-US/004-ground/audio-sounded.mp3': require('../../assets/en-US/004-ground/audio-sounded.mp3'),
  'assets/en-US/004-ground/audio.mp3': require('../../assets/en-US/004-ground/audio.mp3'),
  'assets/en-US/004-ground/great-job.mp3': require('../../assets/en-US/004-ground/great-job.mp3'),
  'assets/en-US/004-ground/no-input.mp3': require('../../assets/en-US/004-ground/no-input.mp3'),
  'assets/en-US/004-ground/prompt.mp3': require('../../assets/en-US/004-ground/prompt.mp3'),
  'assets/en-US/004-ground/try-again.mp3': require('../../assets/en-US/004-ground/try-again.mp3'),
  'assets/en-US/005-i-am-bringing-the-ball/audio.mp3': require('../../assets/en-US/005-i-am-bringing-the-ball/audio.mp3'),
  'assets/en-US/005-i-am-bringing-the-ball/great-job.mp3': require('../../assets/en-US/005-i-am-bringing-the-ball/great-job.mp3'),
  'assets/en-US/005-i-am-bringing-the-ball/no-input.mp3': require('../../assets/en-US/005-i-am-bringing-the-ball/no-input.mp3'),
  'assets/en-US/005-i-am-bringing-the-ball/prompt.mp3': require('../../assets/en-US/005-i-am-bringing-the-ball/prompt.mp3'),
  'assets/en-US/005-i-am-bringing-the-ball/try-again.mp3': require('../../assets/en-US/005-i-am-bringing-the-ball/try-again.mp3'),
  'assets/en-US/006-the-room-is-cool/audio.mp3': require('../../assets/en-US/006-the-room-is-cool/audio.mp3'),
  'assets/en-US/006-the-room-is-cool/great-job.mp3': require('../../assets/en-US/006-the-room-is-cool/great-job.mp3'),
  'assets/en-US/006-the-room-is-cool/no-input.mp3': require('../../assets/en-US/006-the-room-is-cool/no-input.mp3'),
  'assets/en-US/006-the-room-is-cool/prompt.mp3': require('../../assets/en-US/006-the-room-is-cool/prompt.mp3'),
  'assets/en-US/006-the-room-is-cool/try-again.mp3': require('../../assets/en-US/006-the-room-is-cool/try-again.mp3'),
  'assets/en-US/I/audio.mp3': require('../../assets/en-US/I/audio.mp3'),
  'assets/en-US/a/audio.mp3': require('../../assets/en-US/a/audio.mp3'),
  'assets/en-US/b/audio.mp3': require('../../assets/en-US/b/audio.mp3'),
  'assets/en-US/c/audio.mp3': require('../../assets/en-US/c/audio.mp3'),
  'assets/en-US/e/audio.mp3': require('../../assets/en-US/e/audio.mp3'),
  'assets/en-US/g/audio.mp3': require('../../assets/en-US/g/audio.mp3'),
  'assets/en-US/h/audio.mp3': require('../../assets/en-US/h/audio.mp3'),
  'assets/en-US/i/audio.mp3': require('../../assets/en-US/i/audio.mp3'),
  'assets/en-US/l/audio.mp3': require('../../assets/en-US/l/audio.mp3'),
  'assets/en-US/m/audio.mp3': require('../../assets/en-US/m/audio.mp3'),
  'assets/en-US/n/audio.mp3': require('../../assets/en-US/n/audio.mp3'),
  'assets/en-US/o/audio.mp3': require('../../assets/en-US/o/audio.mp3'),
  'assets/en-US/phoneme-d/audio.mp3': require('../../assets/en-US/phoneme-d/audio.mp3'),
  'assets/en-US/phoneme-g/audio.mp3': require('../../assets/en-US/phoneme-g/audio.mp3'),
  'assets/en-US/phoneme-i/audio.mp3': require('../../assets/en-US/phoneme-i/audio.mp3'),
  'assets/en-US/phoneme-n/audio.mp3': require('../../assets/en-US/phoneme-n/audio.mp3'),
  'assets/en-US/phoneme-ou/audio.mp3': require('../../assets/en-US/phoneme-ou/audio.mp3'),
  'assets/en-US/phoneme-p/audio.mp3': require('../../assets/en-US/phoneme-p/audio.mp3'),
  'assets/en-US/phoneme-r/audio.mp3': require('../../assets/en-US/phoneme-r/audio.mp3'),
  'assets/en-US/phoneme-z/audio.mp3': require('../../assets/en-US/phoneme-z/audio.mp3'),
  'assets/en-US/r/audio.mp3': require('../../assets/en-US/r/audio.mp3'),
  'assets/en-US/s/audio.mp3': require('../../assets/en-US/s/audio.mp3'),
  'assets/en-US/t/audio.mp3': require('../../assets/en-US/t/audio.mp3'),
  'assets/en-US/word-am/audio.mp3': require('../../assets/en-US/word-am/audio.mp3'),
  'assets/en-US/word-ball/audio.mp3': require('../../assets/en-US/word-ball/audio.mp3'),
  'assets/en-US/word-bringing/audio.mp3': require('../../assets/en-US/word-bringing/audio.mp3'),
  'assets/en-US/word-cool/audio.mp3': require('../../assets/en-US/word-cool/audio.mp3'),
  'assets/en-US/word-i/audio.mp3': require('../../assets/en-US/word-i/audio.mp3'),
  'assets/en-US/word-is/audio.mp3': require('../../assets/en-US/word-is/audio.mp3'),
  'assets/en-US/word-room/audio.mp3': require('../../assets/en-US/word-room/audio.mp3'),
  'assets/en-US/word-the/audio.mp3': require('../../assets/en-US/word-the/audio.mp3'),
};

/**
 * Get audio source for a given asset path
 * Returns a require() module for local assets, or { uri } for remote URLs
 */
export function getAudioSource(assetPath: string): any {
  // Check if it's a remote URL
  if (assetPath.startsWith('http://') || assetPath.startsWith('https://')) {
    return { uri: assetPath };
  }
  
  // Check if we have this asset mapped
  const mappedAsset = AUDIO_ASSETS[assetPath];
  if (mappedAsset !== undefined) {
    return mappedAsset;
  }
  
  // Fallback: try as URI (might work for some cases)
  console.warn(`Audio asset not found in map: ${assetPath}`);
  return { uri: assetPath };
}

/**
 * Check if an audio asset exists
 */
export function hasAudioAsset(assetPath: string): boolean {
  return assetPath in AUDIO_ASSETS || 
         assetPath.startsWith('http://') || 
         assetPath.startsWith('https://');
}
