/**
 * Audio Asset Map for Static DISTAR Card Audio Files
 * 
 * React Native requires static require() calls for bundled assets.
 * This maps audio asset paths to their require() statements.
 * 
 * Generated by scripts/generate-cards.ts
 * DO NOT EDIT THIS FILE MANUALLY
 * 
 * NOTE: All require() statements must be static (no variables in the path)
 */

// Audio assets for cards - using static require() statements
const AUDIO_ASSETS: Record<string, any> = {
  'assets/en-US/001-b/audio.mp3': require('../../assets/en-US/001-b/audio.mp3'),
  'assets/en-US/001-b/great-job.mp3': require('../../assets/en-US/001-b/great-job.mp3'),
  'assets/en-US/001-b/no-input.mp3': require('../../assets/en-US/001-b/no-input.mp3'),
  'assets/en-US/001-b/prompt.mp3': require('../../assets/en-US/001-b/prompt.mp3'),
  'assets/en-US/001-b/try-again.mp3': require('../../assets/en-US/001-b/try-again.mp3'),
  'assets/en-US/002-y/audio.mp3': require('../../assets/en-US/002-y/audio.mp3'),
  'assets/en-US/002-y/great-job.mp3': require('../../assets/en-US/002-y/great-job.mp3'),
  'assets/en-US/002-y/no-input.mp3': require('../../assets/en-US/002-y/no-input.mp3'),
  'assets/en-US/002-y/prompt.mp3': require('../../assets/en-US/002-y/prompt.mp3'),
  'assets/en-US/002-y/try-again.mp3': require('../../assets/en-US/002-y/try-again.mp3'),
  'assets/en-US/003-qu/audio.mp3': require('../../assets/en-US/003-qu/audio.mp3'),
  'assets/en-US/003-qu/great-job.mp3': require('../../assets/en-US/003-qu/great-job.mp3'),
  'assets/en-US/003-qu/no-input.mp3': require('../../assets/en-US/003-qu/no-input.mp3'),
  'assets/en-US/003-qu/prompt.mp3': require('../../assets/en-US/003-qu/prompt.mp3'),
  'assets/en-US/003-qu/try-again.mp3': require('../../assets/en-US/003-qu/try-again.mp3'),
  'assets/en-US/004-j/audio.mp3': require('../../assets/en-US/004-j/audio.mp3'),
  'assets/en-US/004-j/great-job.mp3': require('../../assets/en-US/004-j/great-job.mp3'),
  'assets/en-US/004-j/no-input.mp3': require('../../assets/en-US/004-j/no-input.mp3'),
  'assets/en-US/004-j/prompt.mp3': require('../../assets/en-US/004-j/prompt.mp3'),
  'assets/en-US/004-j/try-again.mp3': require('../../assets/en-US/004-j/try-again.mp3'),
  'assets/en-US/005-arm/audio-sounded.mp3': require('../../assets/en-US/005-arm/audio-sounded.mp3'),
  'assets/en-US/005-arm/audio.mp3': require('../../assets/en-US/005-arm/audio.mp3'),
  'assets/en-US/005-arm/great-job.mp3': require('../../assets/en-US/005-arm/great-job.mp3'),
  'assets/en-US/005-arm/no-input.mp3': require('../../assets/en-US/005-arm/no-input.mp3'),
  'assets/en-US/005-arm/prompt.mp3': require('../../assets/en-US/005-arm/prompt.mp3'),
  'assets/en-US/005-arm/try-again.mp3': require('../../assets/en-US/005-arm/try-again.mp3'),
  'assets/en-US/006-apex/audio-sounded.mp3': require('../../assets/en-US/006-apex/audio-sounded.mp3'),
  'assets/en-US/006-apex/audio.mp3': require('../../assets/en-US/006-apex/audio.mp3'),
  'assets/en-US/006-apex/great-job.mp3': require('../../assets/en-US/006-apex/great-job.mp3'),
  'assets/en-US/006-apex/no-input.mp3': require('../../assets/en-US/006-apex/no-input.mp3'),
  'assets/en-US/006-apex/prompt.mp3': require('../../assets/en-US/006-apex/prompt.mp3'),
  'assets/en-US/006-apex/try-again.mp3': require('../../assets/en-US/006-apex/try-again.mp3'),
  'assets/en-US/007-your/audio-sounded.mp3': require('../../assets/en-US/007-your/audio-sounded.mp3'),
  'assets/en-US/007-your/audio.mp3': require('../../assets/en-US/007-your/audio.mp3'),
  'assets/en-US/007-your/great-job.mp3': require('../../assets/en-US/007-your/great-job.mp3'),
  'assets/en-US/007-your/no-input.mp3': require('../../assets/en-US/007-your/no-input.mp3'),
  'assets/en-US/007-your/prompt.mp3': require('../../assets/en-US/007-your/prompt.mp3'),
  'assets/en-US/007-your/try-again.mp3': require('../../assets/en-US/007-your/try-again.mp3'),
  'assets/en-US/008-win/audio-sounded.mp3': require('../../assets/en-US/008-win/audio-sounded.mp3'),
  'assets/en-US/008-win/audio.mp3': require('../../assets/en-US/008-win/audio.mp3'),
  'assets/en-US/008-win/great-job.mp3': require('../../assets/en-US/008-win/great-job.mp3'),
  'assets/en-US/008-win/no-input.mp3': require('../../assets/en-US/008-win/no-input.mp3'),
  'assets/en-US/008-win/prompt.mp3': require('../../assets/en-US/008-win/prompt.mp3'),
  'assets/en-US/008-win/try-again.mp3': require('../../assets/en-US/008-win/try-again.mp3'),
  'assets/en-US/009-i-love-to-learn-new-things/audio.mp3': require('../../assets/en-US/009-i-love-to-learn-new-things/audio.mp3'),
  'assets/en-US/009-i-love-to-learn-new-things/great-job.mp3': require('../../assets/en-US/009-i-love-to-learn-new-things/great-job.mp3'),
  'assets/en-US/009-i-love-to-learn-new-things/no-input.mp3': require('../../assets/en-US/009-i-love-to-learn-new-things/no-input.mp3'),
  'assets/en-US/009-i-love-to-learn-new-things/prompt.mp3': require('../../assets/en-US/009-i-love-to-learn-new-things/prompt.mp3'),
  'assets/en-US/009-i-love-to-learn-new-things/try-again.mp3': require('../../assets/en-US/009-i-love-to-learn-new-things/try-again.mp3'),
  'assets/en-US/010-i-will-win/audio.mp3': require('../../assets/en-US/010-i-will-win/audio.mp3'),
  'assets/en-US/010-i-will-win/great-job.mp3': require('../../assets/en-US/010-i-will-win/great-job.mp3'),
  'assets/en-US/010-i-will-win/no-input.mp3': require('../../assets/en-US/010-i-will-win/no-input.mp3'),
  'assets/en-US/010-i-will-win/prompt.mp3': require('../../assets/en-US/010-i-will-win/prompt.mp3'),
  'assets/en-US/010-i-will-win/try-again.mp3': require('../../assets/en-US/010-i-will-win/try-again.mp3'),
  'assets/en-US/011-the-big-bug-is-red/audio.mp3': require('../../assets/en-US/011-the-big-bug-is-red/audio.mp3'),
  'assets/en-US/011-the-big-bug-is-red/great-job.mp3': require('../../assets/en-US/011-the-big-bug-is-red/great-job.mp3'),
  'assets/en-US/011-the-big-bug-is-red/no-input.mp3': require('../../assets/en-US/011-the-big-bug-is-red/no-input.mp3'),
  'assets/en-US/011-the-big-bug-is-red/prompt.mp3': require('../../assets/en-US/011-the-big-bug-is-red/prompt.mp3'),
  'assets/en-US/011-the-big-bug-is-red/try-again.mp3': require('../../assets/en-US/011-the-big-bug-is-red/try-again.mp3'),
  'assets/en-US/012-the-mat-is-flat/audio.mp3': require('../../assets/en-US/012-the-mat-is-flat/audio.mp3'),
  'assets/en-US/012-the-mat-is-flat/great-job.mp3': require('../../assets/en-US/012-the-mat-is-flat/great-job.mp3'),
  'assets/en-US/012-the-mat-is-flat/no-input.mp3': require('../../assets/en-US/012-the-mat-is-flat/no-input.mp3'),
  'assets/en-US/012-the-mat-is-flat/prompt.mp3': require('../../assets/en-US/012-the-mat-is-flat/prompt.mp3'),
  'assets/en-US/012-the-mat-is-flat/try-again.mp3': require('../../assets/en-US/012-the-mat-is-flat/try-again.mp3'),
  'assets/en-US/I/audio.mp3': require('../../assets/en-US/I/audio.mp3'),
  'assets/en-US/a/audio.mp3': require('../../assets/en-US/a/audio.mp3'),
  'assets/en-US/b/audio.mp3': require('../../assets/en-US/b/audio.mp3'),
  'assets/en-US/d/audio.mp3': require('../../assets/en-US/d/audio.mp3'),
  'assets/en-US/e/audio.mp3': require('../../assets/en-US/e/audio.mp3'),
  'assets/en-US/f/audio.mp3': require('../../assets/en-US/f/audio.mp3'),
  'assets/en-US/g/audio.mp3': require('../../assets/en-US/g/audio.mp3'),
  'assets/en-US/h/audio.mp3': require('../../assets/en-US/h/audio.mp3'),
  'assets/en-US/i/audio.mp3': require('../../assets/en-US/i/audio.mp3'),
  'assets/en-US/l/audio.mp3': require('../../assets/en-US/l/audio.mp3'),
  'assets/en-US/m/audio.mp3': require('../../assets/en-US/m/audio.mp3'),
  'assets/en-US/n/audio.mp3': require('../../assets/en-US/n/audio.mp3'),
  'assets/en-US/o/audio.mp3': require('../../assets/en-US/o/audio.mp3'),
  'assets/en-US/phoneme-a/audio.mp3': require('../../assets/en-US/phoneme-a/audio.mp3'),
  'assets/en-US/phoneme-ar/audio.mp3': require('../../assets/en-US/phoneme-ar/audio.mp3'),
  'assets/en-US/phoneme-e/audio.mp3': require('../../assets/en-US/phoneme-e/audio.mp3'),
  'assets/en-US/phoneme-i/audio.mp3': require('../../assets/en-US/phoneme-i/audio.mp3'),
  'assets/en-US/phoneme-m/audio.mp3': require('../../assets/en-US/phoneme-m/audio.mp3'),
  'assets/en-US/phoneme-n/audio.mp3': require('../../assets/en-US/phoneme-n/audio.mp3'),
  'assets/en-US/phoneme-ou/audio.mp3': require('../../assets/en-US/phoneme-ou/audio.mp3'),
  'assets/en-US/phoneme-p/audio.mp3': require('../../assets/en-US/phoneme-p/audio.mp3'),
  'assets/en-US/phoneme-r/audio.mp3': require('../../assets/en-US/phoneme-r/audio.mp3'),
  'assets/en-US/phoneme-w/audio.mp3': require('../../assets/en-US/phoneme-w/audio.mp3'),
  'assets/en-US/phoneme-x/audio.mp3': require('../../assets/en-US/phoneme-x/audio.mp3'),
  'assets/en-US/r/audio.mp3': require('../../assets/en-US/r/audio.mp3'),
  'assets/en-US/s/audio.mp3': require('../../assets/en-US/s/audio.mp3'),
  'assets/en-US/t/audio.mp3': require('../../assets/en-US/t/audio.mp3'),
  'assets/en-US/u/audio.mp3': require('../../assets/en-US/u/audio.mp3'),
  'assets/en-US/v/audio.mp3': require('../../assets/en-US/v/audio.mp3'),
  'assets/en-US/w/audio.mp3': require('../../assets/en-US/w/audio.mp3'),
  'assets/en-US/word-big/audio.mp3': require('../../assets/en-US/word-big/audio.mp3'),
  'assets/en-US/word-bug/audio.mp3': require('../../assets/en-US/word-bug/audio.mp3'),
  'assets/en-US/word-flat/audio.mp3': require('../../assets/en-US/word-flat/audio.mp3'),
  'assets/en-US/word-i/audio.mp3': require('../../assets/en-US/word-i/audio.mp3'),
  'assets/en-US/word-is/audio.mp3': require('../../assets/en-US/word-is/audio.mp3'),
  'assets/en-US/word-learn/audio.mp3': require('../../assets/en-US/word-learn/audio.mp3'),
  'assets/en-US/word-love/audio.mp3': require('../../assets/en-US/word-love/audio.mp3'),
  'assets/en-US/word-mat/audio.mp3': require('../../assets/en-US/word-mat/audio.mp3'),
  'assets/en-US/word-new/audio.mp3': require('../../assets/en-US/word-new/audio.mp3'),
  'assets/en-US/word-red/audio.mp3': require('../../assets/en-US/word-red/audio.mp3'),
  'assets/en-US/word-the/audio.mp3': require('../../assets/en-US/word-the/audio.mp3'),
  'assets/en-US/word-things/audio.mp3': require('../../assets/en-US/word-things/audio.mp3'),
  'assets/en-US/word-to/audio.mp3': require('../../assets/en-US/word-to/audio.mp3'),
  'assets/en-US/word-will/audio.mp3': require('../../assets/en-US/word-will/audio.mp3'),
};

/**
 * Get audio source for a given asset path
 * Returns a require() module for local assets, or { uri } for remote URLs
 */
export function getAudioSource(assetPath: string): any {
  // Check if it's a remote URL
  if (assetPath.startsWith('http://') || assetPath.startsWith('https://')) {
    return { uri: assetPath };
  }
  
  // Check if we have this asset mapped
  const mappedAsset = AUDIO_ASSETS[assetPath];
  if (mappedAsset !== undefined) {
    return mappedAsset;
  }
  
  // Fallback: try as URI (might work for some cases)
  console.warn(`Audio asset not found in map: ${assetPath}`);
  return { uri: assetPath };
}

/**
 * Check if an audio asset exists
 */
export function hasAudioAsset(assetPath: string): boolean {
  return assetPath in AUDIO_ASSETS || 
         assetPath.startsWith('http://') || 
         assetPath.startsWith('https://');
}
