/**
 * Pre-generated DISTAR Cards
 * 
 * This file contains all 6 pre-generated cards following the DISTAR methodology.
 * Generated by scripts/generate-cards.ts
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 */

export interface DistarCard {
  id: string;
  type: 'letter' | 'digraph' | 'word' | 'sentence';
  display: string;
  plainText: string;
  phonemes: string[];
  words?: string[];
  phonemeAudioPaths: string[];
  wordAudioPaths?: string[];
  lesson: number;
  imagePath: string;
  audioPath: string;
  soundedOutPath?: string;
  orthography: {
    macrons: number[];
    small: number[];
    balls: number[];
    arrows: number[];
  };
}

export const DISTAR_CARDS: DistarCard[] = [
  {
    "id": "phoneme-m",
    "type": "letter",
    "display": "m",
    "plainText": "m",
    "phonemes": [
      "m"
    ],
    "phonemeAudioPaths": [
      "assets/sounds/phonemes/m.mp3"
    ],
    "lesson": 1,
    "imagePath": "assets/images/letters/m.png",
    "audioPath": "assets/sounds/phonemes/m.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [
        0
      ],
      "arrows": []
    }
  },
  {
    "id": "phoneme-s",
    "type": "letter",
    "display": "s",
    "plainText": "s",
    "phonemes": [
      "s"
    ],
    "phonemeAudioPaths": [
      "assets/sounds/phonemes/s.mp3"
    ],
    "lesson": 1,
    "imagePath": "assets/images/letters/s.png",
    "audioPath": "assets/sounds/phonemes/s.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": [
        0
      ]
    }
  },
  {
    "id": "word-am",
    "type": "word",
    "display": "am",
    "plainText": "am",
    "phonemes": [
      "a",
      "m"
    ],
    "phonemeAudioPaths": [
      "assets/sounds/phonemes/a.mp3",
      "assets/sounds/phonemes/m.mp3"
    ],
    "lesson": 10,
    "imagePath": "assets/images/words/am.png",
    "audioPath": "assets/sounds/words/am.mp3",
    "soundedOutPath": "assets/sounds/words/am-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "word-at",
    "type": "word",
    "display": "at",
    "plainText": "at",
    "phonemes": [
      "a",
      "t"
    ],
    "phonemeAudioPaths": [
      "assets/sounds/phonemes/a.mp3",
      "assets/sounds/phonemes/t.mp3"
    ],
    "lesson": 10,
    "imagePath": "assets/images/words/at.png",
    "audioPath": "assets/sounds/words/at.mp3",
    "soundedOutPath": "assets/sounds/words/at-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "sentence-the-cat-sat",
    "type": "sentence",
    "display": "the cat sat",
    "plainText": "the cat sat",
    "phonemes": [
      "t",
      "h",
      "e",
      "c",
      "a",
      "t",
      "s",
      "a",
      "t"
    ],
    "words": [
      "the",
      "cat",
      "sat"
    ],
    "phonemeAudioPaths": [
      "assets/sounds/phonemes/t.mp3",
      "assets/sounds/phonemes/h.mp3",
      "assets/sounds/phonemes/e.mp3",
      "assets/sounds/phonemes/c.mp3",
      "assets/sounds/phonemes/a.mp3",
      "assets/sounds/phonemes/t.mp3",
      "assets/sounds/phonemes/s.mp3",
      "assets/sounds/phonemes/a.mp3",
      "assets/sounds/phonemes/t.mp3"
    ],
    "wordAudioPaths": [
      "assets/sounds/words/the.mp3",
      "assets/sounds/words/cat.mp3",
      "assets/sounds/words/sat.mp3"
    ],
    "lesson": 25,
    "imagePath": "assets/images/sentences/the-cat-sat.png",
    "audioPath": "assets/sounds/sentences/the-cat-sat.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "sentence-I-am-sad",
    "type": "sentence",
    "display": "I am sad",
    "plainText": "I am sad",
    "phonemes": [
      "I",
      "a",
      "m",
      "s",
      "a",
      "d"
    ],
    "words": [
      "I",
      "am",
      "sad"
    ],
    "phonemeAudioPaths": [
      "assets/sounds/phonemes/I.mp3",
      "assets/sounds/phonemes/a.mp3",
      "assets/sounds/phonemes/m.mp3",
      "assets/sounds/phonemes/s.mp3",
      "assets/sounds/phonemes/a.mp3",
      "assets/sounds/phonemes/d.mp3"
    ],
    "wordAudioPaths": [
      "assets/sounds/words/I.mp3",
      "assets/sounds/words/am.mp3",
      "assets/sounds/words/sad.mp3"
    ],
    "lesson": 30,
    "imagePath": "assets/images/sentences/I-am-sad.png",
    "audioPath": "assets/sounds/sentences/I-am-sad.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  }
];

/**
 * Get card by ID
 */
export function getCardById(id: string): DistarCard | undefined {
  return DISTAR_CARDS.find(card => card.id === id);
}

/**
 * Get cards for a specific lesson
 */
export function getCardsForLesson(lesson: number): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.lesson === lesson);
}

/**
 * Get all cards up to a lesson
 */
export function getCardsUpToLesson(lesson: number): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.lesson <= lesson);
}

/**
 * Get cards by type
 */
export function getCardsByType(type: DistarCard['type']): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.type === type);
}













