/**
 * Pre-generated DISTAR Cards for locale: en-US
 * 
 * This file contains all 6 pre-generated cards following the DISTAR methodology.
 * Generated by scripts/generate-cards.ts
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 */

export interface DistarCard {
  id: string;
  type: 'letter' | 'digraph' | 'word' | 'sentence';
  display: string;
  plainText: string;
  phonemes: string[];
  words?: string[];
  phonemeAudioPaths: string[];
  wordAudioPaths?: string[];
  lesson: number;
  imagePath: string;
  promptPath: string;
  tryAgainPath: string;
  noInputPath: string;
  greatJobPath: string;
  audioPath: string;
  soundedOutPath?: string;
  orthography: {
    macrons: number[];
    small: number[];
    balls: number[];
    arrows: number[];
  };
}

export const DISTAR_CARDS: DistarCard[] = [
  {
    "id": "001-l",
    "type": "letter",
    "display": "l",
    "plainText": "l",
    "phonemes": [
      "l"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/001-l/audio.mp3"
    ],
    "lesson": 29,
    "imagePath": "assets/en-US/001-l/image.png",
    "promptPath": "assets/en-US/001-l/prompt.mp3",
    "tryAgainPath": "assets/en-US/001-l/try-again.mp3",
    "noInputPath": "assets/en-US/001-l/no-input.mp3",
    "greatJobPath": "assets/en-US/001-l/great-job.mp3",
    "audioPath": "assets/en-US/001-l/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [
        0
      ],
      "arrows": []
    }
  },
  {
    "id": "002-i",
    "type": "letter",
    "display": "i",
    "plainText": "i",
    "phonemes": [
      "i"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/002-i/audio.mp3"
    ],
    "lesson": 14,
    "imagePath": "assets/en-US/002-i/image.png",
    "promptPath": "assets/en-US/002-i/prompt.mp3",
    "tryAgainPath": "assets/en-US/002-i/try-again.mp3",
    "noInputPath": "assets/en-US/002-i/no-input.mp3",
    "greatJobPath": "assets/en-US/002-i/great-job.mp3",
    "audioPath": "assets/en-US/002-i/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [
        0
      ],
      "arrows": []
    }
  },
  {
    "id": "003-big",
    "type": "word",
    "display": "big",
    "plainText": "big",
    "phonemes": [
      "b",
      "i",
      "g"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/phoneme-b/audio.mp3",
      "assets/en-US/002-i/audio.mp3",
      "assets/en-US/phoneme-g/audio.mp3"
    ],
    "lesson": 55,
    "imagePath": "assets/en-US/003-big/image.png",
    "promptPath": "assets/en-US/003-big/prompt.mp3",
    "tryAgainPath": "assets/en-US/003-big/try-again.mp3",
    "noInputPath": "assets/en-US/003-big/no-input.mp3",
    "greatJobPath": "assets/en-US/003-big/great-job.mp3",
    "audioPath": "assets/en-US/003-big/audio.mp3",
    "soundedOutPath": "assets/en-US/003-big/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "004-brain",
    "type": "word",
    "display": "brain",
    "plainText": "brain",
    "phonemes": [
      "b",
      "r",
      "ai",
      "n"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/phoneme-b/audio.mp3",
      "assets/en-US/phoneme-r/audio.mp3",
      "assets/en-US/phoneme-ai/audio.mp3",
      "assets/en-US/phoneme-n/audio.mp3"
    ],
    "lesson": 85,
    "imagePath": "assets/en-US/004-brain/image.png",
    "promptPath": "assets/en-US/004-brain/prompt.mp3",
    "tryAgainPath": "assets/en-US/004-brain/try-again.mp3",
    "noInputPath": "assets/en-US/004-brain/no-input.mp3",
    "greatJobPath": "assets/en-US/004-brain/great-job.mp3",
    "audioPath": "assets/en-US/004-brain/audio.mp3",
    "soundedOutPath": "assets/en-US/004-brain/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "005-she-is-my-best-friend",
    "type": "sentence",
    "display": "she is my best friend",
    "plainText": "she is my best friend",
    "phonemes": [
      "s",
      "h",
      "e",
      "i",
      "s",
      "m",
      "y",
      "b",
      "e",
      "s",
      "t",
      "f",
      "r",
      "i",
      "e",
      "n",
      "d"
    ],
    "words": [
      "she",
      "is",
      "my",
      "best",
      "friend"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/s/audio.mp3",
      "assets/en-US/h/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/i/audio.mp3",
      "assets/en-US/s/audio.mp3",
      "assets/en-US/m/audio.mp3",
      "assets/en-US/y/audio.mp3",
      "assets/en-US/b/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/s/audio.mp3",
      "assets/en-US/t/audio.mp3",
      "assets/en-US/f/audio.mp3",
      "assets/en-US/r/audio.mp3",
      "assets/en-US/i/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/n/audio.mp3",
      "assets/en-US/d/audio.mp3"
    ],
    "wordAudioPaths": [
      "assets/en-US/word-she/audio.mp3",
      "assets/en-US/word-is/audio.mp3",
      "assets/en-US/word-my/audio.mp3",
      "assets/en-US/word-best/audio.mp3",
      "assets/en-US/word-friend/audio.mp3"
    ],
    "lesson": 95,
    "imagePath": "assets/en-US/005-she-is-my-best-friend/image.png",
    "promptPath": "assets/en-US/005-she-is-my-best-friend/prompt.mp3",
    "tryAgainPath": "assets/en-US/005-she-is-my-best-friend/try-again.mp3",
    "noInputPath": "assets/en-US/005-she-is-my-best-friend/no-input.mp3",
    "greatJobPath": "assets/en-US/005-she-is-my-best-friend/great-job.mp3",
    "audioPath": "assets/en-US/005-she-is-my-best-friend/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "006-we-like-to-run-and-play",
    "type": "sentence",
    "display": "we like to run and play",
    "plainText": "we like to run and play",
    "phonemes": [
      "w",
      "e",
      "l",
      "i",
      "k",
      "e",
      "t",
      "o",
      "r",
      "u",
      "n",
      "a",
      "n",
      "d",
      "p",
      "l",
      "a",
      "y"
    ],
    "words": [
      "we",
      "like",
      "to",
      "run",
      "and",
      "play"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/w/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/l/audio.mp3",
      "assets/en-US/i/audio.mp3",
      "assets/en-US/k/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/t/audio.mp3",
      "assets/en-US/o/audio.mp3",
      "assets/en-US/r/audio.mp3",
      "assets/en-US/u/audio.mp3",
      "assets/en-US/n/audio.mp3",
      "assets/en-US/a/audio.mp3",
      "assets/en-US/n/audio.mp3",
      "assets/en-US/d/audio.mp3",
      "assets/en-US/p/audio.mp3",
      "assets/en-US/l/audio.mp3",
      "assets/en-US/a/audio.mp3",
      "assets/en-US/y/audio.mp3"
    ],
    "wordAudioPaths": [
      "assets/en-US/word-we/audio.mp3",
      "assets/en-US/word-like/audio.mp3",
      "assets/en-US/word-to/audio.mp3",
      "assets/en-US/word-run/audio.mp3",
      "assets/en-US/word-and/audio.mp3",
      "assets/en-US/word-play/audio.mp3"
    ],
    "lesson": 45,
    "imagePath": "assets/en-US/006-we-like-to-run-and-play/image.png",
    "promptPath": "assets/en-US/006-we-like-to-run-and-play/prompt.mp3",
    "tryAgainPath": "assets/en-US/006-we-like-to-run-and-play/try-again.mp3",
    "noInputPath": "assets/en-US/006-we-like-to-run-and-play/no-input.mp3",
    "greatJobPath": "assets/en-US/006-we-like-to-run-and-play/great-job.mp3",
    "audioPath": "assets/en-US/006-we-like-to-run-and-play/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  }
];

export const LOCALE = 'en-US';

/**
 * Get card by ID
 */
export function getCardById(id: string): DistarCard | undefined {
  return DISTAR_CARDS.find(card => card.id === id);
}

/**
 * Get cards for a specific lesson
 */
export function getCardsForLesson(lesson: number): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.lesson === lesson);
}

/**
 * Get all cards up to a lesson
 */
export function getCardsUpToLesson(lesson: number): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.lesson <= lesson);
}

/**
 * Get cards by type
 */
export function getCardsByType(type: DistarCard['type']): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.type === type);
}
