/**
 * Pre-generated DISTAR Cards for locale: en-US
 * 
 * This file contains all 12 pre-generated cards following the DISTAR methodology.
 * Generated by scripts/generate-cards.ts
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 */

export interface DistarCard {
  id: string;
  type: 'letter' | 'digraph' | 'word' | 'sentence';
  display: string;
  plainText: string;
  phonemes: string[];
  words?: string[];
  phonemeAudioPaths: string[];
  wordAudioPaths?: string[];
  lesson: number;
  imagePath: string;
  promptPath: string;
  tryAgainPath: string;
  noInputPath: string;
  greatJobPath: string;
  audioPath: string;
  soundedOutPath?: string;
  orthography: {
    macrons: number[];
    small: number[];
    balls: number[];
    arrows: number[];
  };
}

export const DISTAR_CARDS: DistarCard[] = [
  {
    "id": "001-b",
    "type": "letter",
    "display": "b",
    "plainText": "b",
    "phonemes": [
      "b"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/001-b/audio.mp3"
    ],
    "lesson": 55,
    "imagePath": "assets/en-US/001-b/image.png",
    "promptPath": "assets/en-US/001-b/prompt.mp3",
    "tryAgainPath": "assets/en-US/001-b/try-again.mp3",
    "noInputPath": "assets/en-US/001-b/no-input.mp3",
    "greatJobPath": "assets/en-US/001-b/great-job.mp3",
    "audioPath": "assets/en-US/001-b/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [
        0
      ],
      "arrows": []
    }
  },
  {
    "id": "002-y",
    "type": "letter",
    "display": "y",
    "plainText": "y",
    "phonemes": [
      "y"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/002-y/audio.mp3"
    ],
    "lesson": 61,
    "imagePath": "assets/en-US/002-y/image.png",
    "promptPath": "assets/en-US/002-y/prompt.mp3",
    "tryAgainPath": "assets/en-US/002-y/try-again.mp3",
    "noInputPath": "assets/en-US/002-y/no-input.mp3",
    "greatJobPath": "assets/en-US/002-y/great-job.mp3",
    "audioPath": "assets/en-US/002-y/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [
        0
      ],
      "arrows": []
    }
  },
  {
    "id": "003-qu",
    "type": "digraph",
    "display": "qu",
    "plainText": "qu",
    "phonemes": [
      "qu"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/003-qu/audio.mp3"
    ],
    "lesson": 75,
    "imagePath": "assets/en-US/003-qu/image.png",
    "promptPath": "assets/en-US/003-qu/prompt.mp3",
    "tryAgainPath": "assets/en-US/003-qu/try-again.mp3",
    "noInputPath": "assets/en-US/003-qu/no-input.mp3",
    "greatJobPath": "assets/en-US/003-qu/great-job.mp3",
    "audioPath": "assets/en-US/003-qu/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "004-j",
    "type": "letter",
    "display": "j",
    "plainText": "j",
    "phonemes": [
      "j"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/004-j/audio.mp3"
    ],
    "lesson": 67,
    "imagePath": "assets/en-US/004-j/image.png",
    "promptPath": "assets/en-US/004-j/prompt.mp3",
    "tryAgainPath": "assets/en-US/004-j/try-again.mp3",
    "noInputPath": "assets/en-US/004-j/no-input.mp3",
    "greatJobPath": "assets/en-US/004-j/great-job.mp3",
    "audioPath": "assets/en-US/004-j/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [
        0
      ],
      "arrows": []
    }
  },
  {
    "id": "005-arm",
    "type": "word",
    "display": "arm",
    "plainText": "arm",
    "phonemes": [
      "ar",
      "m"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/phoneme-ar/audio.mp3",
      "assets/en-US/phoneme-m/audio.mp3"
    ],
    "lesson": 45,
    "imagePath": "assets/en-US/005-arm/image.png",
    "promptPath": "assets/en-US/005-arm/prompt.mp3",
    "tryAgainPath": "assets/en-US/005-arm/try-again.mp3",
    "noInputPath": "assets/en-US/005-arm/no-input.mp3",
    "greatJobPath": "assets/en-US/005-arm/great-job.mp3",
    "audioPath": "assets/en-US/005-arm/audio.mp3",
    "soundedOutPath": "assets/en-US/005-arm/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "006-apex",
    "type": "word",
    "display": "apex",
    "plainText": "apex",
    "phonemes": [
      "a",
      "p",
      "e",
      "x"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/phoneme-a/audio.mp3",
      "assets/en-US/phoneme-p/audio.mp3",
      "assets/en-US/phoneme-e/audio.mp3",
      "assets/en-US/phoneme-x/audio.mp3"
    ],
    "lesson": 75,
    "imagePath": "assets/en-US/006-apex/image.png",
    "promptPath": "assets/en-US/006-apex/prompt.mp3",
    "tryAgainPath": "assets/en-US/006-apex/try-again.mp3",
    "noInputPath": "assets/en-US/006-apex/no-input.mp3",
    "greatJobPath": "assets/en-US/006-apex/great-job.mp3",
    "audioPath": "assets/en-US/006-apex/audio.mp3",
    "soundedOutPath": "assets/en-US/006-apex/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "007-your",
    "type": "word",
    "display": "your",
    "plainText": "your",
    "phonemes": [
      "y",
      "ou",
      "r"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/002-y/audio.mp3",
      "assets/en-US/phoneme-ou/audio.mp3",
      "assets/en-US/phoneme-r/audio.mp3"
    ],
    "lesson": 95,
    "imagePath": "assets/en-US/007-your/image.png",
    "promptPath": "assets/en-US/007-your/prompt.mp3",
    "tryAgainPath": "assets/en-US/007-your/try-again.mp3",
    "noInputPath": "assets/en-US/007-your/no-input.mp3",
    "greatJobPath": "assets/en-US/007-your/great-job.mp3",
    "audioPath": "assets/en-US/007-your/audio.mp3",
    "soundedOutPath": "assets/en-US/007-your/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "008-win",
    "type": "word",
    "display": "win",
    "plainText": "win",
    "phonemes": [
      "w",
      "i",
      "n"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/phoneme-w/audio.mp3",
      "assets/en-US/phoneme-i/audio.mp3",
      "assets/en-US/phoneme-n/audio.mp3"
    ],
    "lesson": 35,
    "imagePath": "assets/en-US/008-win/image.png",
    "promptPath": "assets/en-US/008-win/prompt.mp3",
    "tryAgainPath": "assets/en-US/008-win/try-again.mp3",
    "noInputPath": "assets/en-US/008-win/no-input.mp3",
    "greatJobPath": "assets/en-US/008-win/great-job.mp3",
    "audioPath": "assets/en-US/008-win/audio.mp3",
    "soundedOutPath": "assets/en-US/008-win/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "009-i-love-to-learn-new-things",
    "type": "sentence",
    "display": "I love to learn new things",
    "plainText": "I love to learn new things",
    "phonemes": [
      "I",
      "l",
      "o",
      "v",
      "e",
      "t",
      "o",
      "l",
      "e",
      "a",
      "r",
      "n",
      "n",
      "e",
      "w",
      "t",
      "h",
      "i",
      "n",
      "g",
      "s"
    ],
    "words": [
      "I",
      "love",
      "to",
      "learn",
      "new",
      "things"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/I/audio.mp3",
      "assets/en-US/l/audio.mp3",
      "assets/en-US/o/audio.mp3",
      "assets/en-US/v/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/t/audio.mp3",
      "assets/en-US/o/audio.mp3",
      "assets/en-US/l/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/a/audio.mp3",
      "assets/en-US/r/audio.mp3",
      "assets/en-US/n/audio.mp3",
      "assets/en-US/n/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/w/audio.mp3",
      "assets/en-US/t/audio.mp3",
      "assets/en-US/h/audio.mp3",
      "assets/en-US/i/audio.mp3",
      "assets/en-US/n/audio.mp3",
      "assets/en-US/g/audio.mp3",
      "assets/en-US/s/audio.mp3"
    ],
    "wordAudioPaths": [
      "assets/en-US/word-i/audio.mp3",
      "assets/en-US/word-love/audio.mp3",
      "assets/en-US/word-to/audio.mp3",
      "assets/en-US/word-learn/audio.mp3",
      "assets/en-US/word-new/audio.mp3",
      "assets/en-US/word-things/audio.mp3"
    ],
    "lesson": 100,
    "imagePath": "assets/en-US/009-i-love-to-learn-new-things/image.png",
    "promptPath": "assets/en-US/009-i-love-to-learn-new-things/prompt.mp3",
    "tryAgainPath": "assets/en-US/009-i-love-to-learn-new-things/try-again.mp3",
    "noInputPath": "assets/en-US/009-i-love-to-learn-new-things/no-input.mp3",
    "greatJobPath": "assets/en-US/009-i-love-to-learn-new-things/great-job.mp3",
    "audioPath": "assets/en-US/009-i-love-to-learn-new-things/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "010-i-will-win",
    "type": "sentence",
    "display": "I will win",
    "plainText": "I will win",
    "phonemes": [
      "I",
      "w",
      "i",
      "l",
      "l",
      "w",
      "i",
      "n"
    ],
    "words": [
      "I",
      "will",
      "win"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/I/audio.mp3",
      "assets/en-US/w/audio.mp3",
      "assets/en-US/i/audio.mp3",
      "assets/en-US/l/audio.mp3",
      "assets/en-US/l/audio.mp3",
      "assets/en-US/w/audio.mp3",
      "assets/en-US/i/audio.mp3",
      "assets/en-US/n/audio.mp3"
    ],
    "wordAudioPaths": [
      "assets/en-US/word-i/audio.mp3",
      "assets/en-US/word-will/audio.mp3",
      "assets/en-US/008-win/audio.mp3"
    ],
    "lesson": 32,
    "imagePath": "assets/en-US/010-i-will-win/image.png",
    "promptPath": "assets/en-US/010-i-will-win/prompt.mp3",
    "tryAgainPath": "assets/en-US/010-i-will-win/try-again.mp3",
    "noInputPath": "assets/en-US/010-i-will-win/no-input.mp3",
    "greatJobPath": "assets/en-US/010-i-will-win/great-job.mp3",
    "audioPath": "assets/en-US/010-i-will-win/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "011-the-big-bug-is-red",
    "type": "sentence",
    "display": "the big bug is red",
    "plainText": "the big bug is red",
    "phonemes": [
      "t",
      "h",
      "e",
      "b",
      "i",
      "g",
      "b",
      "u",
      "g",
      "i",
      "s",
      "r",
      "e",
      "d"
    ],
    "words": [
      "the",
      "big",
      "bug",
      "is",
      "red"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/t/audio.mp3",
      "assets/en-US/h/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/b/audio.mp3",
      "assets/en-US/i/audio.mp3",
      "assets/en-US/g/audio.mp3",
      "assets/en-US/b/audio.mp3",
      "assets/en-US/u/audio.mp3",
      "assets/en-US/g/audio.mp3",
      "assets/en-US/i/audio.mp3",
      "assets/en-US/s/audio.mp3",
      "assets/en-US/r/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/d/audio.mp3"
    ],
    "wordAudioPaths": [
      "assets/en-US/word-the/audio.mp3",
      "assets/en-US/word-big/audio.mp3",
      "assets/en-US/word-bug/audio.mp3",
      "assets/en-US/word-is/audio.mp3",
      "assets/en-US/word-red/audio.mp3"
    ],
    "lesson": 58,
    "imagePath": "assets/en-US/011-the-big-bug-is-red/image.png",
    "promptPath": "assets/en-US/011-the-big-bug-is-red/prompt.mp3",
    "tryAgainPath": "assets/en-US/011-the-big-bug-is-red/try-again.mp3",
    "noInputPath": "assets/en-US/011-the-big-bug-is-red/no-input.mp3",
    "greatJobPath": "assets/en-US/011-the-big-bug-is-red/great-job.mp3",
    "audioPath": "assets/en-US/011-the-big-bug-is-red/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "012-the-mat-is-flat",
    "type": "sentence",
    "display": "the mat is flat",
    "plainText": "the mat is flat",
    "phonemes": [
      "t",
      "h",
      "e",
      "m",
      "a",
      "t",
      "i",
      "s",
      "f",
      "l",
      "a",
      "t"
    ],
    "words": [
      "the",
      "mat",
      "is",
      "flat"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/t/audio.mp3",
      "assets/en-US/h/audio.mp3",
      "assets/en-US/e/audio.mp3",
      "assets/en-US/m/audio.mp3",
      "assets/en-US/a/audio.mp3",
      "assets/en-US/t/audio.mp3",
      "assets/en-US/i/audio.mp3",
      "assets/en-US/s/audio.mp3",
      "assets/en-US/f/audio.mp3",
      "assets/en-US/l/audio.mp3",
      "assets/en-US/a/audio.mp3",
      "assets/en-US/t/audio.mp3"
    ],
    "wordAudioPaths": [
      "assets/en-US/word-the/audio.mp3",
      "assets/en-US/word-mat/audio.mp3",
      "assets/en-US/word-is/audio.mp3",
      "assets/en-US/word-flat/audio.mp3"
    ],
    "lesson": 20,
    "imagePath": "assets/en-US/012-the-mat-is-flat/image.png",
    "promptPath": "assets/en-US/012-the-mat-is-flat/prompt.mp3",
    "tryAgainPath": "assets/en-US/012-the-mat-is-flat/try-again.mp3",
    "noInputPath": "assets/en-US/012-the-mat-is-flat/no-input.mp3",
    "greatJobPath": "assets/en-US/012-the-mat-is-flat/great-job.mp3",
    "audioPath": "assets/en-US/012-the-mat-is-flat/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  }
];

export const LOCALE = 'en-US';

/**
 * Get card by ID
 */
export function getCardById(id: string): DistarCard | undefined {
  return DISTAR_CARDS.find(card => card.id === id);
}

/**
 * Get cards for a specific lesson
 */
export function getCardsForLesson(lesson: number): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.lesson === lesson);
}

/**
 * Get all cards up to a lesson
 */
export function getCardsUpToLesson(lesson: number): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.lesson <= lesson);
}

/**
 * Get cards by type
 */
export function getCardsByType(type: DistarCard['type']): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.type === type);
}
