/**
 * Pre-generated DISTAR Cards for locale: en-US
 * 
 * This file contains all 12 pre-generated cards following the DISTAR methodology.
 * Generated by scripts/generate-cards.ts
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 */

export interface DistarCard {
  id: string;
  type: 'letter' | 'digraph' | 'word' | 'sentence';
  display: string;
  plainText: string;
  phonemes: string[];
  words?: string[];
  phonemeAudioPaths: string[];
  wordAudioPaths?: string[];
  lesson: number;
  imagePath: string;
  promptPath: string;
  tryAgainPath: string;
  noInputPath: string;
  greatJobPath: string;
  audioPath: string;
  soundedOutPath?: string;
  orthography: {
    macrons: number[];
    small: number[];
    balls: number[];
    arrows: number[];
  };
}

export const DISTAR_CARDS: DistarCard[] = [
  {
    "id": "001-sh",
    "type": "digraph",
    "display": "sh",
    "plainText": "sh",
    "phonemes": [
      "sh"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/001-sh/audio.mp3"
    ],
    "lesson": 35,
    "imagePath": "assets/en-US/001-sh/image.png",
    "promptPath": "assets/en-US/001-sh/prompt.mp3",
    "tryAgainPath": "assets/en-US/001-sh/try-again.mp3",
    "noInputPath": "assets/en-US/001-sh/no-input.mp3",
    "greatJobPath": "assets/en-US/001-sh/great-job.mp3",
    "audioPath": "assets/en-US/001-sh/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "002-m",
    "type": "letter",
    "display": "m",
    "plainText": "m",
    "phonemes": [
      "m"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/002-m/audio.mp3"
    ],
    "lesson": 1,
    "imagePath": "assets/en-US/002-m/image.png",
    "promptPath": "assets/en-US/002-m/prompt.mp3",
    "tryAgainPath": "assets/en-US/002-m/try-again.mp3",
    "noInputPath": "assets/en-US/002-m/no-input.mp3",
    "greatJobPath": "assets/en-US/002-m/great-job.mp3",
    "audioPath": "assets/en-US/002-m/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [
        0
      ],
      "arrows": []
    }
  },
  {
    "id": "003-ch",
    "type": "digraph",
    "display": "ch",
    "plainText": "ch",
    "phonemes": [
      "ch"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/003-ch/audio.mp3"
    ],
    "lesson": 51,
    "imagePath": "assets/en-US/003-ch/image.png",
    "promptPath": "assets/en-US/003-ch/prompt.mp3",
    "tryAgainPath": "assets/en-US/003-ch/try-again.mp3",
    "noInputPath": "assets/en-US/003-ch/no-input.mp3",
    "greatJobPath": "assets/en-US/003-ch/great-job.mp3",
    "audioPath": "assets/en-US/003-ch/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "004-wh",
    "type": "digraph",
    "display": "wh",
    "plainText": "wh",
    "phonemes": [
      "wh"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/004-wh/audio.mp3"
    ],
    "lesson": 69,
    "imagePath": "assets/en-US/004-wh/image.png",
    "promptPath": "assets/en-US/004-wh/prompt.mp3",
    "tryAgainPath": "assets/en-US/004-wh/try-again.mp3",
    "noInputPath": "assets/en-US/004-wh/no-input.mp3",
    "greatJobPath": "assets/en-US/004-wh/great-job.mp3",
    "audioPath": "assets/en-US/004-wh/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "005-leave",
    "type": "word",
    "display": "leave",
    "plainText": "leave",
    "phonemes": [
      "l",
      "ea",
      "v"
    ],
    "lesson": 95,
    "imagePath": "assets/en-US/005-leave/image.png",
    "promptPath": "assets/en-US/005-leave/prompt.mp3",
    "tryAgainPath": "assets/en-US/005-leave/try-again.mp3",
    "noInputPath": "assets/en-US/005-leave/no-input.mp3",
    "greatJobPath": "assets/en-US/005-leave/great-job.mp3",
    "audioPath": "assets/en-US/005-leave/audio.mp3",
    "soundedOutPath": "assets/en-US/005-leave/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "006-chin",
    "type": "word",
    "display": "chin",
    "plainText": "chin",
    "phonemes": [
      "ch",
      "i",
      "n"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/003-ch/audio.mp3"
    ],
    "lesson": 55,
    "imagePath": "assets/en-US/006-chin/image.png",
    "promptPath": "assets/en-US/006-chin/prompt.mp3",
    "tryAgainPath": "assets/en-US/006-chin/try-again.mp3",
    "noInputPath": "assets/en-US/006-chin/no-input.mp3",
    "greatJobPath": "assets/en-US/006-chin/great-job.mp3",
    "audioPath": "assets/en-US/006-chin/audio.mp3",
    "soundedOutPath": "assets/en-US/006-chin/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "007-whim",
    "type": "word",
    "display": "whim",
    "plainText": "whim",
    "phonemes": [
      "wh",
      "i",
      "m"
    ],
    "phonemeAudioPaths": [
      "assets/en-US/004-wh/audio.mp3",
      "assets/en-US/002-m/audio.mp3"
    ],
    "lesson": 65,
    "imagePath": "assets/en-US/007-whim/image.png",
    "promptPath": "assets/en-US/007-whim/prompt.mp3",
    "tryAgainPath": "assets/en-US/007-whim/try-again.mp3",
    "noInputPath": "assets/en-US/007-whim/no-input.mp3",
    "greatJobPath": "assets/en-US/007-whim/great-job.mp3",
    "audioPath": "assets/en-US/007-whim/audio.mp3",
    "soundedOutPath": "assets/en-US/007-whim/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "008-stool",
    "type": "word",
    "display": "stool",
    "plainText": "stool",
    "phonemes": [
      "s",
      "t",
      "oo",
      "l"
    ],
    "lesson": 65,
    "imagePath": "assets/en-US/008-stool/image.png",
    "promptPath": "assets/en-US/008-stool/prompt.mp3",
    "tryAgainPath": "assets/en-US/008-stool/try-again.mp3",
    "noInputPath": "assets/en-US/008-stool/no-input.mp3",
    "greatJobPath": "assets/en-US/008-stool/great-job.mp3",
    "audioPath": "assets/en-US/008-stool/audio.mp3",
    "soundedOutPath": "assets/en-US/008-stool/audio-sounded.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "009-i-like-to-sing",
    "type": "sentence",
    "display": "I like to sing",
    "plainText": "I like to sing",
    "phonemes": [
      "I",
      "l",
      "i",
      "k",
      "e",
      "t",
      "o",
      "s",
      "i",
      "n",
      "g"
    ],
    "words": [
      "I",
      "like",
      "to",
      "sing"
    ],
    "lesson": 52,
    "imagePath": "assets/en-US/009-i-like-to-sing/image.png",
    "promptPath": "assets/en-US/009-i-like-to-sing/prompt.mp3",
    "tryAgainPath": "assets/en-US/009-i-like-to-sing/try-again.mp3",
    "noInputPath": "assets/en-US/009-i-like-to-sing/no-input.mp3",
    "greatJobPath": "assets/en-US/009-i-like-to-sing/great-job.mp3",
    "audioPath": "assets/en-US/009-i-like-to-sing/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "010-the-children-are-playing-outside",
    "type": "sentence",
    "display": "the children are playing outside",
    "plainText": "the children are playing outside",
    "phonemes": [
      "t",
      "h",
      "e",
      "c",
      "h",
      "i",
      "l",
      "d",
      "r",
      "e",
      "n",
      "a",
      "r",
      "e",
      "p",
      "l",
      "a",
      "y",
      "i",
      "n",
      "g",
      "o",
      "u",
      "t",
      "s",
      "i",
      "d",
      "e"
    ],
    "words": [
      "the",
      "children",
      "are",
      "playing",
      "outside"
    ],
    "lesson": 93,
    "imagePath": "assets/en-US/010-the-children-are-playing-outside/image.png",
    "promptPath": "assets/en-US/010-the-children-are-playing-outside/prompt.mp3",
    "tryAgainPath": "assets/en-US/010-the-children-are-playing-outside/try-again.mp3",
    "noInputPath": "assets/en-US/010-the-children-are-playing-outside/no-input.mp3",
    "greatJobPath": "assets/en-US/010-the-children-are-playing-outside/great-job.mp3",
    "audioPath": "assets/en-US/010-the-children-are-playing-outside/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "011-we-are-learning-to-read-well",
    "type": "sentence",
    "display": "we are learning to read well",
    "plainText": "we are learning to read well",
    "phonemes": [
      "w",
      "e",
      "a",
      "r",
      "e",
      "l",
      "e",
      "a",
      "r",
      "n",
      "i",
      "n",
      "g",
      "t",
      "o",
      "r",
      "e",
      "a",
      "d",
      "w",
      "e",
      "l",
      "l"
    ],
    "words": [
      "we",
      "are",
      "learning",
      "to",
      "read",
      "well"
    ],
    "lesson": 95,
    "imagePath": "assets/en-US/011-we-are-learning-to-read-well/image.png",
    "promptPath": "assets/en-US/011-we-are-learning-to-read-well/prompt.mp3",
    "tryAgainPath": "assets/en-US/011-we-are-learning-to-read-well/try-again.mp3",
    "noInputPath": "assets/en-US/011-we-are-learning-to-read-well/no-input.mp3",
    "greatJobPath": "assets/en-US/011-we-are-learning-to-read-well/great-job.mp3",
    "audioPath": "assets/en-US/011-we-are-learning-to-read-well/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  },
  {
    "id": "012-she-went-to-school-today",
    "type": "sentence",
    "display": "she went to school today",
    "plainText": "she went to school today",
    "phonemes": [
      "s",
      "h",
      "e",
      "w",
      "e",
      "n",
      "t",
      "t",
      "o",
      "s",
      "c",
      "h",
      "o",
      "o",
      "l",
      "t",
      "o",
      "d",
      "a",
      "y"
    ],
    "words": [
      "she",
      "went",
      "to",
      "school",
      "today"
    ],
    "lesson": 92,
    "imagePath": "assets/en-US/012-she-went-to-school-today/image.png",
    "promptPath": "assets/en-US/012-she-went-to-school-today/prompt.mp3",
    "tryAgainPath": "assets/en-US/012-she-went-to-school-today/try-again.mp3",
    "noInputPath": "assets/en-US/012-she-went-to-school-today/no-input.mp3",
    "greatJobPath": "assets/en-US/012-she-went-to-school-today/great-job.mp3",
    "audioPath": "assets/en-US/012-she-went-to-school-today/audio.mp3",
    "orthography": {
      "macrons": [],
      "small": [],
      "balls": [],
      "arrows": []
    }
  }
];

export const LOCALE = 'en-US';

/**
 * Get card by ID
 */
export function getCardById(id: string): DistarCard | undefined {
  return DISTAR_CARDS.find(card => card.id === id);
}

/**
 * Get cards for a specific lesson
 */
export function getCardsForLesson(lesson: number): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.lesson === lesson);
}

/**
 * Get all cards up to a lesson
 */
export function getCardsUpToLesson(lesson: number): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.lesson <= lesson);
}

/**
 * Get cards by type
 */
export function getCardsByType(type: DistarCard['type']): DistarCard[] {
  return DISTAR_CARDS.filter(card => card.type === type);
}
